name: Build Extension

on:
  push:
    branches:
      - main
      - principal # Caso o tradutor tenha mudado o nome da sua branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew assembleDebug
        continue-on-error: true # Para a gente ver o erro se falhar

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: nebulosa-extension
          path: "**/*.apk"
